version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
    environment:
      NEO4J_AUTH: neo4j/Test123@
