version: '3.8'

services:
  app:
    build: ./
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NEO4j_URL=bolt://host.docker.internal:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=Test123@
      - PORT=3000
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
    environment:
      NEO4J_AUTH: neo4j/Test123@
